version: "3"

services:
  app:
    build: .
    labels:
      - traefik.enable=true
      - traefik.http.routers.colorgen.rule=Host(`c.devminer.xyz`)
      - traefik.http.routers.colorgen.entrypoints=websecure
      - traefik.http.services.colorgen-service.loadbalancer.server.port=3000
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    name: web_default
    external: true
